sudo: required
services:
  -docker

before_install:
  - docker build -t kcarron/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kcarron/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-637423191600"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
